@API_HostAddress = https://localhost:7275

# @name Login
POST {{API_HostAddress}}/api/authentication/Login
Content-Type: application/json
{
  "email": "jukman2@gmail.com",
  "password": "Kode1234!"
}

###

# @name Register
POST {{API_HostAddress}}/api/authentication/Register
Content-Type: application/json
{
  "email": "jukman2@gmail.com",
  "password": "Kode1234!"
}