ALTER TABLE user_account ALTER COLUMN id DROP DEFAULT;
ALTER TABLE user_token ALTER COLUMN id DROP DEFAULT;
ALTER TABLE user_platform_integration ALTER COLUMN id DROP DEFAULT;
ALTER TABLE post ALTER COLUMN id DROP DEFAULT;
ALTER TABLE post_media ALTER COLUMN id DROP DEFAULT;